### ISSUE TITLE
Global install fails

### ISSUE THREAD

**Issue by schickling** [wercker/step-npm-install#4]
If you install something globally (with the `-g` flag) it fails due to permission conflicts. I guess you need to change permissions for npm or run the global installation as root.

**Comment by yoshuawuyts** [comment]
Closing. Issue seems resolved and there hasn't been activity for almost a year. Let me know if this is still problematic and I'll reopen it gladly.

**Comment by mbrevda** [comment]
yes @yoshuawuyts it is still an issue. The documentation states that one can pass options like `-g foo` for a global install. In fact, global install requires sudo. Either the docs need to be updated to not include the -g example, or - and more preferably - the step should receive an actual `sudo: true` option

**Comment by yoshuawuyts** [comment]
@mbrevda yeah, that's a reasonable solution. Alternatively you could do it the _npm way_™ and install all binaries locally. E.g. you can run stuff out of [npm scripts](https://docs.npmjs.com/misc/scripts) or reference `./node_modules/.bin/<module name>` directly. 

Regardless of that, the docs on this module are incorrect and need to be updated since `-g` doesn't work. PR's for a `sudo` mode are welcome!

**Comment by nodesocket** [comment]
Recommend not installing packages globally if at all possible and just put inside of `package.json`. That way when run via `npm run` the paths will be resolved and you can just reference the package binary.
